Feature/stp 196 upgrade tf version
StratusGrid/terraform-aws-multiaccount-application-pipeline pull request #8
Opened 2023-12-06 15:13 UTC by jheison-rodriguez

## Change description

- Upgrade the TF version.
- Add tflint plugin version.
- https://stratusgrid.atlassian.net/browse/STP-196

## Type of change
- [ ] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [x] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2023-12-06 20:28 UTC, fernandoPedraza-sg approved these changes
The updates to terraform look good to me

2023-12-11 11:46 UTC, JoseMotto-sg requested changes
is this .tflint required? if not, we can just delete it.

2023-12-11 15:03 UTC, JoseMotto-sg commented
@jheison-rodriguez It's OK to go with the latest unless there is a specific requirement, so if there is not it's ok to remove it.

2023-12-12 09:21 UTC, JoseMotto-sg approved these changes

2023-12-12 15:11 UTC, merged